online-mode=false
enforce-secure-profile=false
server-port=25566
server-ip=
motd=Hill School 175th Anniversary Competition
max-players=120
allow-flight=true
gamemode=adventure
force-gamemode=false
spawn-protection=0
enable-command-block=false
enable-rcon=false
enable-query=false
white-list=false
view-distance=10
simulation-distance=6
network-compression-threshold=256
sync-chunk-writes=false
level-name=world
pvp=false
